### ISSUE TITLE
Add expiration time to rollout 

### ISSUE THREAD

**Issue by LitalFiverr** [fiverr/rollout_dashboard#12]
add expiration time to rollout -  default of one month. (let the owner edit it from one week to 3 months)
and inform the owner regarding getting close to the expiration time by slack message and/or email. 
on expiration time - delete the rollout automatically. 

also give the user an option to extend expiration by max of 3 months.

**Comment by omrilotan** [comment]
we'll need indefinite expiration IMO

**Comment by LitalFiverr** [comment]
I don't agree.. rollout should have expiration just as AB test should have expiration . 
it shouldn't be forgotten or be used on the code as permanent logic . and the expiration will enforce it.

**Comment by yossi-eynav** [comment]
@LitalFiverr 
closing this issue, we can talk about it in private
