### ISSUE TITLE
move all calls to rollout_service to the backend, so it could be secured

### ISSUE THREAD

**Issue by dorongutman** [fiverr/rollout_dashboard#19]
Right now rollout_service is open to the public for all reads.
I want to set both the dashboard and the service in the same VPC - service in a private subnet, dashboard in a public subnet, publicly accessible - and so protect the service from being accessed by bad people.
The dashboard tries to make the api calls to the service in the browser, so I can't protect the service.

**Comment by yossi-eynav** [comment]
You can restrict all reads with the access token
